#!/usr/bin/env python3
import argparse
import json

from pn_common import (
    RemoteScriptError,
    add_connection_args,
    call_mcp_tool_json,
    emit_result,
    fail,
    normalize_mcp_url,
    resolve_corpus,
    resolve_token
)


def add_project_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--project")
    parser.add_argument("--target-domain")
    parser.add_argument("--target-problem")
    parser.add_argument("--method", help="Optional validated method-lineage anchor for structural-gap and innovation-pattern analysis.")
    parser.add_argument("--max-depth", type=int, help="Maximum validated method-lineage traversal depth.")
    parser.add_argument("--lineage-limit", type=int, help="Maximum validated method lineages retained.")
    parser.add_argument("--persistent-assumption-min-papers", type=int, help="Distinct-paper threshold for subtractive persistent-assumption gaps (default: 2).")
    parser.add_argument("--pattern-limit", type=int, help="Maximum research-action pattern matches per structural gap (default: 2).")
    parser.add_argument("--pattern-card-json", action="append", default=[], help="Optional caller-supplied research-action card as a JSON object.")
    parser.add_argument("--candidate-mechanism", help="Optional concrete mechanism text for regression and collision query planning.")
    parser.add_argument("--removed-component", action="append", default=[], help="Assumption or component removed/replaced by the candidate mechanism.")
    parser.add_argument("--idea-component", action="append", default=[], help="Idea component for innovation_evidence_pack composition-collision audit.")
    parser.add_argument("--coverage-area", action="append", default=[], help="Coverage area override for innovation_evidence_pack evidence-sufficiency audit.")
    parser.add_argument("--constraint", action="append", default=[])
    parser.add_argument("--role", action="append", default=[])
    parser.add_argument("--auto-discover-sources", action="store_true", help="Compatibility flag for material-pack workflows; source discovery is generated by default.")
    parser.add_argument("--prefer-domain", action="append", default=[], help="Preferred source domain for the graph-native near/far router.")
    parser.add_argument("--exclude-domain", action="append", default=[], help="Source domain excluded from the graph-native near/far router.")
    parser.add_argument("--near-source-domain", action="append", default=[], help="Explicit domain to treat as a near-source method domain.")
    parser.add_argument("--far-source-domain", action="append", default=[], help="Explicit domain to treat as a far-source story domain.")
    parser.add_argument("--min-domain-distance", type=float, help="Minimum source-domain distance before proximal_leakage is marked.")
    parser.add_argument("--max-proximal-results", type=int, help="Maximum proximal-leakage source domains retained.")
    parser.add_argument("--source-domain-limit", type=int, help="Maximum source domains returned by the router.")
    parser.add_argument("--include-provider-evidence", action="store_true", help="Opt in to bounded read-only Semantic Scholar snippet evidence.")
    parser.add_argument("--provider-evidence-limit", type=int, help="Maximum provider snippet hits retained per query.")
    parser.add_argument("--persist-provider-evidence", action="store_true", help="Persist provider evidence snippets into the project evidence cart. Requires --project.")
    parser.add_argument("--provider-evidence-persist-limit", type=int, help="Maximum provider evidence snippets persisted into the evidence cart.")
    parser.add_argument("--provider-evidence-query-limit", type=int, help="Maximum generated queries sent to provider evidence search.")
    parser.add_argument("--provider-evidence-timeout-ms", type=int, help="Timeout in milliseconds for each provider evidence request.")
    parser.add_argument("--provider-evidence-fallback-to-abstract", action="store_true", help="Hydrate degenerate provider snippets with abstracts when available.")
    parser.add_argument("--include-live-discovery-evidence", action="store_true", help="Opt in to bounded idea_catalyst live_discovery evidence.")
    parser.add_argument("--run-live-idea-catalyst-if-needed", action="store_true", help="Run bounded idea_catalyst live_discovery only when committed-graph role evidence is sparse.")
    parser.add_argument("--live-discovery-fallback-if-sparse", action="store_true", help="Alias for --run-live-idea-catalyst-if-needed.")
    parser.add_argument("--live-discovery-sparse-role-threshold", type=int, help="Number of sparse requested roles required before sparse live-discovery fallback runs.")
    parser.add_argument("--live-discovery-sparse-min-score", type=float, help="Minimum committed-graph search score counted as non-sparse for sparse live-discovery fallback.")
    parser.add_argument("--persist-live-discovery-evidence", action="store_true", help="Persist live-discovery spans/fragments into the project evidence cart. Requires --project.")
    parser.add_argument("--live-discovery-num-questions", type=int, help="Maximum target research questions used by live discovery.")
    parser.add_argument("--live-discovery-source-domain-limit", type=int, help="Maximum source domains used by live discovery.")
    parser.add_argument("--live-discovery-max-papers-per-query", type=int, help="Maximum snippet papers retrieved per live-discovery query.")
    parser.add_argument("--live-discovery-source-relevance-threshold", type=float, help="Paper-level source relevance ratio threshold for live discovery.")
    parser.add_argument("--live-discovery-idea-fragment-limit", type=int, help="Maximum live-discovery idea fragments retained.")
    parser.add_argument("--live-discovery-persist-limit", type=int, help="Maximum live-discovery evidence items persisted into the evidence cart.")
    parser.add_argument("--live-discovery-timeout-ms", type=int, help="Timeout in milliseconds for each live-discovery provider request.")
    parser.add_argument("--include-literature-discovery-evidence", action="store_true", help="Opt in to bounded literature_discovery search/resolve evidence.")
    parser.add_argument("--run-literature-discovery-if-sparse", action="store_true", help="Run bounded literature_discovery only when committed-graph role evidence is sparse.")
    parser.add_argument("--literature-discovery-fallback-if-sparse", action="store_true", help="Alias for --run-literature-discovery-if-sparse.")
    parser.add_argument("--literature-discovery-seed-provider-papers", action="store_true", help="Pass provider evidence hits into literature_discovery as exact seed papers when both evidence layers are enabled.")
    parser.add_argument("--literature-discovery-provider-seed-limit", type=int, help="Maximum provider evidence hits passed into literature_discovery as exact seed papers.")
    parser.add_argument("--literature-discovery-seed-live-papers", action="store_true", help="Pass live-discovery supporting papers into literature_discovery as exact seed papers when both evidence layers are enabled.")
    parser.add_argument("--literature-discovery-live-seed-limit", type=int, help="Maximum live-discovery supporting papers passed into literature_discovery as exact seed papers.")
    parser.add_argument("--literature-discovery-resolve-sources", action=argparse.BooleanOptionalAction, default=None, help="Resolve legal full-text sources during opt-in literature discovery evidence.")
    parser.add_argument("--literature-discovery-allow-downloads", action=argparse.BooleanOptionalAction, default=None, help="Allow opt-in literature discovery source resolution to stage legal markdown/open-PDF downloads.")
    parser.add_argument("--submit-literature-discovery-imports", action="store_true", help="Submit resolved literature_discovery full-text sources to the import queue.")
    parser.add_argument("--process-literature-discovery-imports", action="store_true", help="Run the import worker after submitting resolved literature_discovery sources.")
    parser.add_argument("--literature-discovery-max-queries", type=int, help="Maximum generated literature_discovery queries.")
    parser.add_argument("--literature-discovery-max-results-per-query", type=int, help="Maximum provider results retained per literature_discovery query.")
    parser.add_argument("--literature-discovery-max-candidates", type=int, help="Maximum merged literature_discovery candidates retained.")
    parser.add_argument("--literature-discovery-max-downloads", type=int, help="Maximum legal full-text downloads staged by literature_discovery.")
    parser.add_argument("--literature-discovery-max-imported", type=int, help="Maximum resolved sources submitted when import submission is enabled.")
    parser.add_argument("--literature-discovery-import-max-passes", type=int, help="Maximum import worker passes when processing literature_discovery imports.")
    parser.add_argument("--literature-discovery-import-batch-enabled", action=argparse.BooleanOptionalAction, default=None, help="Enable worker-side logical batching for processed literature_discovery imports.")
    parser.add_argument("--literature-discovery-import-batch-max-tasks", type=int, help="Maximum import tasks reserved into one logical batch for processed literature_discovery imports.")
    parser.add_argument("--limit", type=int)
    parser.add_argument("--output-dir")


def add_seed_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--seed-paper-json", action="append", default=[], help="JSON object for one seed paper.")
    parser.add_argument("--seed-papers-file", help="JSON file containing a seed paper array.")


def add_overlay_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--project", required=True)
    parser.add_argument("--action")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--actor")


def add_paper_selector_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--paper-id")
    parser.add_argument("--paper-title")
    parser.add_argument("--source-key")


def parse_seed_papers(args) -> list:
    seeds = []
    for raw in getattr(args, "seed_paper_json", []) or []:
        seeds.append(json.loads(raw))
    if getattr(args, "seed_papers_file", None):
        with open(args.seed_papers_file, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
        if isinstance(payload, list):
            seeds.extend(payload)
        elif isinstance(payload, dict) and isinstance(payload.get("seedPapers"), list):
            seeds.extend(payload["seedPapers"])
        else:
            raise RemoteScriptError("--seed-papers-file must contain a JSON array or {seedPapers: [...]}.")
    return seeds


def parse_json_values(values, label: str) -> list:
    parsed = []
    for raw in values or []:
        parsed.append(json.loads(raw))
    return parsed


def parse_args():
    parser = argparse.ArgumentParser(description="Assemble Agent-facing PaperNexus research materials over remote HTTP MCP.")
    add_connection_args(parser)
    subparsers = parser.add_subparsers(dest="command", required=True)

    pack = subparsers.add_parser("research-material-pack")
    add_project_args(pack)
    add_seed_args(pack)

    structural = subparsers.add_parser("structural-gap-pack")
    add_project_args(structural)
    add_seed_args(structural)

    patterns = subparsers.add_parser("innovation-pattern-pack")
    add_project_args(patterns)
    add_seed_args(patterns)

    innovation = subparsers.add_parser("innovation-evidence-pack")
    add_project_args(innovation)
    add_seed_args(innovation)

    discovery = subparsers.add_parser("source-discovery-plan")
    add_project_args(discovery)
    add_seed_args(discovery)

    requisitions = subparsers.add_parser("import-requisition-pack")
    add_project_args(requisitions)
    add_seed_args(requisitions)

    negative = subparsers.add_parser("negative-evidence-pack")
    add_project_args(negative)
    negative.add_argument("--time-window")

    paper = subparsers.add_parser("paper-material-view")
    paper.add_argument("--paper-id")
    paper.add_argument("--paper-title")
    paper.add_argument("--source-key")
    paper.add_argument("--identifier")
    paper.add_argument("--doi")
    paper.add_argument("--arxiv-id")
    paper.add_argument("--pmid")
    paper.add_argument("--pmcid")
    paper.add_argument("--chunk-limit", type=int)
    paper.add_argument("--output-dir")

    cost = subparsers.add_parser("experiment-cost-materials")
    cost.add_argument("--project")
    cost.add_argument("--paper-id")
    cost.add_argument("--paper-title")
    cost.add_argument("--source-key")
    cost.add_argument("--identifier")
    cost.add_argument("--doi")
    cost.add_argument("--arxiv-id")
    cost.add_argument("--pmid")
    cost.add_argument("--pmcid")
    cost.add_argument("--chunk-limit", type=int)
    cost.add_argument("--include-cost-llm-extraction", action="store_true", help="Opt in to bounded LLM structured extraction for experiment-cost materials.")
    cost.add_argument("--cost-llm-record-limit", type=int, help="Maximum paper material records sent to the opt-in cost LLM extractor.")
    cost.add_argument("--cost-llm-max-input-chars", type=int, help="Maximum characters sent to the opt-in cost LLM extractor.")
    cost.add_argument("--cost-llm-provider", help="Optional LLM provider override for opt-in cost extraction.")
    cost.add_argument("--cost-llm-model", help="Optional LLM model override for opt-in cost extraction.")
    cost.add_argument("--cost-llm-base-url", help="Optional LLM base URL override for opt-in cost extraction.")
    cost.add_argument("--cost-llm-api-key-env", help="Optional environment variable name containing the cost-extraction LLM API key.")
    cost.add_argument("--cost-llm-timeout-ms", type=int, help="Timeout in milliseconds for opt-in cost LLM extraction.")
    cost.add_argument("--cost-llm-max-tokens", type=int, help="Maximum output tokens for opt-in cost LLM extraction.")
    cost.add_argument("--output-dir")

    role_overlay = subparsers.add_parser("paper-role-overlay")
    add_overlay_common_args(role_overlay)
    add_paper_selector_args(role_overlay)
    role_overlay.add_argument("--role", action="append", default=[])
    role_overlay.add_argument("--role-id")
    role_overlay.add_argument("--layer")
    role_overlay.add_argument("--judgment-type")
    role_overlay.add_argument("--confidence")
    role_overlay.add_argument("--evidence-id", action="append", default=[])
    role_overlay.add_argument("--note")

    evidence = subparsers.add_parser("evidence-cart")
    add_overlay_common_args(evidence)
    add_paper_selector_args(evidence)
    evidence.add_argument("--evidence-id")
    evidence.add_argument("--item-type")
    evidence.add_argument("--source-type")
    evidence.add_argument("--source-id")
    evidence.add_argument("--role")
    evidence.add_argument("--text")
    evidence.add_argument("--tag", action="append", default=[])
    evidence.add_argument("--note")
    evidence.add_argument("--provenance-json", action="append", default=[], help="JSON provenance object.")
    evidence.add_argument("--output-dir")

    workflow = subparsers.add_parser("workflow-state")
    add_overlay_common_args(workflow)
    workflow.add_argument("--workflow-state-json", help="JSON object merged into workflow state.")
    workflow.add_argument("--hypothesis")
    workflow.add_argument("--current-stage")
    workflow.add_argument("--accepted-direction", action="append", default=[])
    workflow.add_argument("--rejected-direction", action="append", default=[])
    workflow.add_argument("--open-question", action="append", default=[])
    workflow.add_argument("--needed-material", action="append", default=[])
    workflow.add_argument("--note")

    return parser.parse_args()


def common_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "targetDomain": args.target_domain,
        "targetProblem": args.target_problem,
        "method": args.method,
        "maxDepth": args.max_depth,
        "lineageLimit": args.lineage_limit,
        "persistentAssumptionMinPapers": args.persistent_assumption_min_papers,
        "patternLimit": args.pattern_limit,
        "patternCards": parse_json_values(args.pattern_card_json, "--pattern-card-json"),
        "candidateMechanism": args.candidate_mechanism,
        "removedComponents": args.removed_component,
        "ideaComponents": args.idea_component,
        "coverageAreas": args.coverage_area,
        "constraints": args.constraint,
        "roles": args.role,
        "autoDiscoverSources": args.auto_discover_sources,
        "preferDomains": args.prefer_domain,
        "excludeDomains": args.exclude_domain,
        "nearSourceDomains": args.near_source_domain,
        "farSourceDomains": args.far_source_domain,
        "minDomainDistance": args.min_domain_distance,
        "maxProximalResults": args.max_proximal_results,
        "sourceDomainLimit": args.source_domain_limit,
        "includeProviderEvidence": args.include_provider_evidence,
        "providerEvidenceLimit": args.provider_evidence_limit,
        "persistProviderEvidence": args.persist_provider_evidence,
        "providerEvidencePersistLimit": args.provider_evidence_persist_limit,
        "providerEvidenceQueryLimit": args.provider_evidence_query_limit,
        "providerEvidenceTimeoutMs": args.provider_evidence_timeout_ms,
        "providerEvidenceFallbackToAbstract": args.provider_evidence_fallback_to_abstract,
        "includeLiveDiscoveryEvidence": args.include_live_discovery_evidence,
        "runLiveIdeaCatalystIfNeeded": args.run_live_idea_catalyst_if_needed,
        "liveDiscoveryFallbackIfSparse": args.live_discovery_fallback_if_sparse,
        "liveDiscoverySparseRoleThreshold": args.live_discovery_sparse_role_threshold,
        "liveDiscoverySparseMinScore": args.live_discovery_sparse_min_score,
        "persistLiveDiscoveryEvidence": args.persist_live_discovery_evidence,
        "liveDiscoveryNumQuestions": args.live_discovery_num_questions,
        "liveDiscoverySourceDomainLimit": args.live_discovery_source_domain_limit,
        "liveDiscoveryMaxPapersPerQuery": args.live_discovery_max_papers_per_query,
        "liveDiscoverySourceRelevanceThreshold": args.live_discovery_source_relevance_threshold,
        "liveDiscoveryIdeaFragmentLimit": args.live_discovery_idea_fragment_limit,
        "liveDiscoveryPersistLimit": args.live_discovery_persist_limit,
        "liveDiscoveryTimeoutMs": args.live_discovery_timeout_ms,
        "includeLiteratureDiscoveryEvidence": args.include_literature_discovery_evidence,
        "runLiteratureDiscoveryIfSparse": args.run_literature_discovery_if_sparse,
        "literatureDiscoveryFallbackIfSparse": args.literature_discovery_fallback_if_sparse,
        "literatureDiscoverySeedProviderPapers": args.literature_discovery_seed_provider_papers,
        "literatureDiscoveryProviderSeedLimit": args.literature_discovery_provider_seed_limit,
        "literatureDiscoverySeedLivePapers": args.literature_discovery_seed_live_papers,
        "literatureDiscoveryLiveSeedLimit": args.literature_discovery_live_seed_limit,
        "literatureDiscoveryResolveSources": args.literature_discovery_resolve_sources,
        "literatureDiscoveryAllowDownloads": args.literature_discovery_allow_downloads,
        "submitLiteratureDiscoveryImports": args.submit_literature_discovery_imports,
        "processLiteratureDiscoveryImports": args.process_literature_discovery_imports,
        "literatureDiscoveryMaxQueries": args.literature_discovery_max_queries,
        "literatureDiscoveryMaxResultsPerQuery": args.literature_discovery_max_results_per_query,
        "literatureDiscoveryMaxCandidates": args.literature_discovery_max_candidates,
        "literatureDiscoveryMaxDownloads": args.literature_discovery_max_downloads,
        "literatureDiscoveryMaxImported": args.literature_discovery_max_imported,
        "literatureDiscoveryImportMaxPasses": args.literature_discovery_import_max_passes,
        "literatureDiscoveryImportBatchEnabled": args.literature_discovery_import_batch_enabled,
        "literatureDiscoveryImportBatchMaxTasks": args.literature_discovery_import_batch_max_tasks,
        "limit": args.limit,
        "outputDir": args.output_dir,
        "seedPapers": parse_seed_papers(args),
        "timeWindow": getattr(args, "time_window", None)
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [])}


def paper_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "identifier": args.identifier,
        "doi": args.doi,
        "arxivId": args.arxiv_id,
        "pmid": args.pmid,
        "pmcid": args.pmcid,
        "chunkLimit": args.chunk_limit,
        "outputDir": args.output_dir
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [])}


def cost_payload(args, corpus: str) -> dict:
    payload = paper_payload(args, corpus)
    if getattr(args, "project", None):
        payload["project"] = args.project
    payload.update({
        "includeCostLlmExtraction": getattr(args, "include_cost_llm_extraction", False),
        "costLlmRecordLimit": getattr(args, "cost_llm_record_limit", None),
        "costLlmMaxInputChars": getattr(args, "cost_llm_max_input_chars", None),
        "costLlmProvider": getattr(args, "cost_llm_provider", None),
        "costLlmModel": getattr(args, "cost_llm_model", None),
        "costLlmBaseUrl": getattr(args, "cost_llm_base_url", None),
        "costLlmApiKeyEnv": getattr(args, "cost_llm_api_key_env", None),
        "costLlmTimeoutMs": getattr(args, "cost_llm_timeout_ms", None),
        "costLlmMaxTokens": getattr(args, "cost_llm_max_tokens", None)
    })
    return {key: value for key, value in payload.items() if value not in (None, "", [])}


def role_overlay_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "roles": args.role,
        "roleId": args.role_id,
        "layer": args.layer,
        "judgmentType": args.judgment_type,
        "confidence": args.confidence,
        "supportingEvidenceIds": args.evidence_id,
        "notes": args.note
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def evidence_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "evidenceId": args.evidence_id,
        "itemType": args.item_type,
        "sourceType": args.source_type,
        "sourceId": args.source_id,
        "role": args.role,
        "text": args.text,
        "tags": args.tag,
        "notes": args.note,
        "provenance": parse_json_values(args.provenance_json, "--provenance-json"),
        "outputDir": args.output_dir
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def workflow_payload(args, corpus: str) -> dict:
    workflow_state = json.loads(args.workflow_state_json) if args.workflow_state_json else None
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "workflowState": workflow_state,
        "hypothesis": args.hypothesis,
        "currentStage": args.current_stage,
        "acceptedDirections": args.accepted_direction,
        "rejectedDirections": args.rejected_direction,
        "openQuestions": args.open_question,
        "neededMaterials": args.needed_material,
        "notes": args.note
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def main() -> int:
    args = parse_args()
    try:
        mcp_url = normalize_mcp_url(args.mcp_url, args.api_base)
        token = resolve_token(args.token)
        corpus = resolve_corpus(args.corpus, mcp_url, token, timeout=args.request_timeout)

        operation = args.command.replace("-", "_")
        if operation == "paper_material_view":
            payload = paper_payload(args, corpus)
        elif operation == "experiment_cost_materials":
            payload = cost_payload(args, corpus)
        elif operation == "paper_role_overlay":
            payload = role_overlay_payload(args, corpus)
        elif operation == "evidence_cart":
            payload = evidence_payload(args, corpus)
        elif operation == "workflow_state":
            payload = workflow_payload(args, corpus)
        else:
            payload = common_payload(args, corpus)
        payload["operation"] = operation

        result = call_mcp_tool_json(
            mcp_url,
            token,
            "agent_materials",
            payload,
            timeout=args.request_timeout
        )
        return emit_result(result, args.json)
    except (RemoteScriptError, json.JSONDecodeError) as exc:
        return fail(str(exc), args.json)


if __name__ == "__main__":
    raise SystemExit(main())
