#!/usr/bin/env python3
import argparse
import json

from pn_common import (
    RemoteScriptError,
    add_connection_args,
    call_mcp_tool_json,
    emit_result,
    fail,
    normalize_mcp_url,
    resolve_corpus,
    resolve_token
)


def add_project_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--project")
    parser.add_argument("--target-domain")
    parser.add_argument("--target-problem")
    parser.add_argument("--constraint", action="append", default=[])
    parser.add_argument("--role", action="append", default=[])
    parser.add_argument("--auto-discover-sources", action="store_true", help="Compatibility flag for material-pack workflows; source discovery is generated by default.")
    parser.add_argument("--prefer-domain", action="append", default=[], help="Preferred source domain for the graph-native near/far router.")
    parser.add_argument("--exclude-domain", action="append", default=[], help="Source domain excluded from the graph-native near/far router.")
    parser.add_argument("--near-source-domain", action="append", default=[], help="Explicit domain to treat as a near-source method domain.")
    parser.add_argument("--far-source-domain", action="append", default=[], help="Explicit domain to treat as a far-source story domain.")
    parser.add_argument("--min-domain-distance", type=float, help="Minimum source-domain distance before proximal_leakage is marked.")
    parser.add_argument("--max-proximal-results", type=int, help="Maximum proximal-leakage source domains retained.")
    parser.add_argument("--source-domain-limit", type=int, help="Maximum source domains returned by the router.")
    parser.add_argument("--include-provider-evidence", action="store_true", help="Opt in to bounded read-only Semantic Scholar snippet evidence.")
    parser.add_argument("--provider-evidence-limit", type=int, help="Maximum provider snippet hits retained per query.")
    parser.add_argument("--persist-provider-evidence", action="store_true", help="Persist provider evidence snippets into the project evidence cart. Requires --project.")
    parser.add_argument("--provider-evidence-persist-limit", type=int, help="Maximum provider evidence snippets persisted into the evidence cart.")
    parser.add_argument("--provider-evidence-query-limit", type=int, help="Maximum generated queries sent to provider evidence search.")
    parser.add_argument("--provider-evidence-timeout-ms", type=int, help="Timeout in milliseconds for each provider evidence request.")
    parser.add_argument("--provider-evidence-fallback-to-abstract", action="store_true", help="Hydrate degenerate provider snippets with abstracts when available.")
    parser.add_argument("--limit", type=int)
    parser.add_argument("--output-dir")


def add_seed_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--seed-paper-json", action="append", default=[], help="JSON object for one seed paper.")
    parser.add_argument("--seed-papers-file", help="JSON file containing a seed paper array.")


def add_overlay_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--project", required=True)
    parser.add_argument("--action")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--actor")


def add_paper_selector_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--paper-id")
    parser.add_argument("--paper-title")
    parser.add_argument("--source-key")


def parse_seed_papers(args) -> list:
    seeds = []
    for raw in getattr(args, "seed_paper_json", []) or []:
        seeds.append(json.loads(raw))
    if getattr(args, "seed_papers_file", None):
        with open(args.seed_papers_file, "r", encoding="utf-8") as handle:
            payload = json.load(handle)
        if isinstance(payload, list):
            seeds.extend(payload)
        elif isinstance(payload, dict) and isinstance(payload.get("seedPapers"), list):
            seeds.extend(payload["seedPapers"])
        else:
            raise RemoteScriptError("--seed-papers-file must contain a JSON array or {seedPapers: [...]}.")
    return seeds


def parse_json_values(values, label: str) -> list:
    parsed = []
    for raw in values or []:
        parsed.append(json.loads(raw))
    return parsed


def parse_args():
    parser = argparse.ArgumentParser(description="Assemble Agent-facing PaperNexus research materials over remote HTTP MCP.")
    add_connection_args(parser)
    subparsers = parser.add_subparsers(dest="command", required=True)

    pack = subparsers.add_parser("research-material-pack")
    add_project_args(pack)
    add_seed_args(pack)

    discovery = subparsers.add_parser("source-discovery-plan")
    add_project_args(discovery)
    add_seed_args(discovery)

    requisitions = subparsers.add_parser("import-requisition-pack")
    add_project_args(requisitions)
    add_seed_args(requisitions)

    negative = subparsers.add_parser("negative-evidence-pack")
    add_project_args(negative)
    negative.add_argument("--time-window")

    paper = subparsers.add_parser("paper-material-view")
    paper.add_argument("--paper-id")
    paper.add_argument("--paper-title")
    paper.add_argument("--source-key")
    paper.add_argument("--identifier")
    paper.add_argument("--doi")
    paper.add_argument("--arxiv-id")
    paper.add_argument("--pmid")
    paper.add_argument("--pmcid")
    paper.add_argument("--chunk-limit", type=int)
    paper.add_argument("--output-dir")

    cost = subparsers.add_parser("experiment-cost-materials")
    cost.add_argument("--project")
    cost.add_argument("--paper-id")
    cost.add_argument("--paper-title")
    cost.add_argument("--source-key")
    cost.add_argument("--identifier")
    cost.add_argument("--doi")
    cost.add_argument("--arxiv-id")
    cost.add_argument("--pmid")
    cost.add_argument("--pmcid")
    cost.add_argument("--chunk-limit", type=int)
    cost.add_argument("--output-dir")

    role_overlay = subparsers.add_parser("paper-role-overlay")
    add_overlay_common_args(role_overlay)
    add_paper_selector_args(role_overlay)
    role_overlay.add_argument("--role", action="append", default=[])
    role_overlay.add_argument("--role-id")
    role_overlay.add_argument("--layer")
    role_overlay.add_argument("--judgment-type")
    role_overlay.add_argument("--confidence")
    role_overlay.add_argument("--evidence-id", action="append", default=[])
    role_overlay.add_argument("--note")

    evidence = subparsers.add_parser("evidence-cart")
    add_overlay_common_args(evidence)
    add_paper_selector_args(evidence)
    evidence.add_argument("--evidence-id")
    evidence.add_argument("--item-type")
    evidence.add_argument("--source-type")
    evidence.add_argument("--source-id")
    evidence.add_argument("--role")
    evidence.add_argument("--text")
    evidence.add_argument("--tag", action="append", default=[])
    evidence.add_argument("--note")
    evidence.add_argument("--provenance-json", action="append", default=[], help="JSON provenance object.")
    evidence.add_argument("--output-dir")

    workflow = subparsers.add_parser("workflow-state")
    add_overlay_common_args(workflow)
    workflow.add_argument("--workflow-state-json", help="JSON object merged into workflow state.")
    workflow.add_argument("--hypothesis")
    workflow.add_argument("--current-stage")
    workflow.add_argument("--accepted-direction", action="append", default=[])
    workflow.add_argument("--rejected-direction", action="append", default=[])
    workflow.add_argument("--open-question", action="append", default=[])
    workflow.add_argument("--needed-material", action="append", default=[])
    workflow.add_argument("--note")

    return parser.parse_args()


def common_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "targetDomain": args.target_domain,
        "targetProblem": args.target_problem,
        "constraints": args.constraint,
        "roles": args.role,
        "autoDiscoverSources": args.auto_discover_sources,
        "preferDomains": args.prefer_domain,
        "excludeDomains": args.exclude_domain,
        "nearSourceDomains": args.near_source_domain,
        "farSourceDomains": args.far_source_domain,
        "minDomainDistance": args.min_domain_distance,
        "maxProximalResults": args.max_proximal_results,
        "sourceDomainLimit": args.source_domain_limit,
        "includeProviderEvidence": args.include_provider_evidence,
        "providerEvidenceLimit": args.provider_evidence_limit,
        "persistProviderEvidence": args.persist_provider_evidence,
        "providerEvidencePersistLimit": args.provider_evidence_persist_limit,
        "providerEvidenceQueryLimit": args.provider_evidence_query_limit,
        "providerEvidenceTimeoutMs": args.provider_evidence_timeout_ms,
        "providerEvidenceFallbackToAbstract": args.provider_evidence_fallback_to_abstract,
        "limit": args.limit,
        "outputDir": args.output_dir,
        "seedPapers": parse_seed_papers(args),
        "timeWindow": getattr(args, "time_window", None)
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [])}


def paper_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "identifier": args.identifier,
        "doi": args.doi,
        "arxivId": args.arxiv_id,
        "pmid": args.pmid,
        "pmcid": args.pmcid,
        "chunkLimit": args.chunk_limit,
        "outputDir": args.output_dir
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [])}


def cost_payload(args, corpus: str) -> dict:
    payload = paper_payload(args, corpus)
    if getattr(args, "project", None):
        payload["project"] = args.project
    return payload


def role_overlay_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "roles": args.role,
        "roleId": args.role_id,
        "layer": args.layer,
        "judgmentType": args.judgment_type,
        "confidence": args.confidence,
        "supportingEvidenceIds": args.evidence_id,
        "notes": args.note
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def evidence_payload(args, corpus: str) -> dict:
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "paperId": args.paper_id,
        "paperTitle": args.paper_title,
        "sourceKey": args.source_key,
        "evidenceId": args.evidence_id,
        "itemType": args.item_type,
        "sourceType": args.source_type,
        "sourceId": args.source_id,
        "role": args.role,
        "text": args.text,
        "tags": args.tag,
        "notes": args.note,
        "provenance": parse_json_values(args.provenance_json, "--provenance-json"),
        "outputDir": args.output_dir
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def workflow_payload(args, corpus: str) -> dict:
    workflow_state = json.loads(args.workflow_state_json) if args.workflow_state_json else None
    payload = {
        "corpus": corpus,
        "project": args.project,
        "action": args.action,
        "dryRun": args.dry_run,
        "actor": args.actor,
        "workflowState": workflow_state,
        "hypothesis": args.hypothesis,
        "currentStage": args.current_stage,
        "acceptedDirections": args.accepted_direction,
        "rejectedDirections": args.rejected_direction,
        "openQuestions": args.open_question,
        "neededMaterials": args.needed_material,
        "notes": args.note
    }
    return {key: value for key, value in payload.items() if value not in (None, "", [], False)}


def main() -> int:
    args = parse_args()
    try:
        mcp_url = normalize_mcp_url(args.mcp_url, args.api_base)
        token = resolve_token(args.token)
        corpus = resolve_corpus(args.corpus, mcp_url, token, timeout=args.request_timeout)

        operation = args.command.replace("-", "_")
        if operation == "paper_material_view":
            payload = paper_payload(args, corpus)
        elif operation == "experiment_cost_materials":
            payload = cost_payload(args, corpus)
        elif operation == "paper_role_overlay":
            payload = role_overlay_payload(args, corpus)
        elif operation == "evidence_cart":
            payload = evidence_payload(args, corpus)
        elif operation == "workflow_state":
            payload = workflow_payload(args, corpus)
        else:
            payload = common_payload(args, corpus)
        payload["operation"] = operation

        result = call_mcp_tool_json(
            mcp_url,
            token,
            "agent_materials",
            payload,
            timeout=args.request_timeout
        )
        return emit_result(result, args.json)
    except (RemoteScriptError, json.JSONDecodeError) as exc:
        return fail(str(exc), args.json)


if __name__ == "__main__":
    raise SystemExit(main())
