export const NODE_TYPES = {
  CORPUS: 'Corpus',
  PAPER: 'Paper',
  PROBLEM: 'Problem',
  CLAIM: 'Claim',
  FINDING: 'Finding',
  METHOD: 'Method',
  DATASET: 'Dataset',
  BENCHMARK: 'Benchmark',
  METRIC: 'Metric',
  LIMITATION: 'Limitation',
  ASSUMPTION: 'Assumption',
  EVIDENCE: 'Evidence',
  FUTURE_DIRECTION: 'FutureDirection',
  RESEARCH_GOAL: 'ResearchGoal'
};

export const GRAPH_LAYERS = {
  CORPUS: 'CorpusLayer',
  DOCUMENT: 'DocumentLayer',
  PROBLEM: 'ProblemLayer',
  METHOD: 'MethodLayer',
  CLAIM: 'ClaimLayer',
  CONSTRAINT: 'ConstraintLayer',
  EVIDENCE: 'EvidenceLayer',
  EVALUATION: 'EvaluationLayer',
  FUTURE: 'FutureLayer',
  GOAL: 'GoalLayer'
};

export const NODE_TYPE_TO_LAYER = {
  [NODE_TYPES.CORPUS]: GRAPH_LAYERS.CORPUS,
  [NODE_TYPES.PAPER]: GRAPH_LAYERS.DOCUMENT,
  [NODE_TYPES.PROBLEM]: GRAPH_LAYERS.PROBLEM,
  [NODE_TYPES.METHOD]: GRAPH_LAYERS.METHOD,
  [NODE_TYPES.CLAIM]: GRAPH_LAYERS.CLAIM,
  [NODE_TYPES.FINDING]: GRAPH_LAYERS.CLAIM,
  [NODE_TYPES.LIMITATION]: GRAPH_LAYERS.CONSTRAINT,
  [NODE_TYPES.ASSUMPTION]: GRAPH_LAYERS.CONSTRAINT,
  [NODE_TYPES.EVIDENCE]: GRAPH_LAYERS.EVIDENCE,
  [NODE_TYPES.DATASET]: GRAPH_LAYERS.EVALUATION,
  [NODE_TYPES.BENCHMARK]: GRAPH_LAYERS.EVALUATION,
  [NODE_TYPES.METRIC]: GRAPH_LAYERS.EVALUATION,
  [NODE_TYPES.FUTURE_DIRECTION]: GRAPH_LAYERS.FUTURE,
  [NODE_TYPES.RESEARCH_GOAL]: GRAPH_LAYERS.GOAL
};

export const EDGE_TYPES = {
  CONTAINS: 'CONTAINS',
  SOLVES: 'SOLVES',
  USES: 'USES',
  EVALUATES_ON: 'EVALUATES_ON',
  BENCHMARKED_ON: 'BENCHMARKED_ON',
  REPORTS: 'REPORTS',
  REPORTS_FINDING: 'REPORTS_FINDING',
  CLAIMS: 'CLAIMS',
  HAS_LIMITATION: 'HAS_LIMITATION',
  ASSUMES: 'ASSUMES',
  SUGGESTS_FUTURE: 'SUGGESTS_FUTURE',
  SUPPORTED_BY: 'SUPPORTED_BY',
  OBSERVED_ON: 'OBSERVED_ON',
  MEASURED_BY: 'MEASURED_BY',
  APPLIES_TO: 'APPLIES_TO',
  TRANSFERABLE_TO: 'TRANSFERABLE_TO',
  REQUIRES: 'REQUIRES',
  DEPENDS_ON: 'DEPENDS_ON',
  FAILS_UNDER: 'FAILS_UNDER',
  HAS_GAP: 'HAS_GAP',
  RELATED_TO: 'RELATED_TO',
  SIMILAR_TO: 'SIMILAR_TO',
  COMPATIBLE_WITH: 'COMPATIBLE_WITH',
  COMBINES_WITH: 'COMBINES_WITH',
  MAY_BE_ADDRESSED_BY: 'MAY_BE_ADDRESSED_BY',
  CONTRADICTS: 'CONTRADICTS',
  CITES: 'CITES',
  LEADS_TO: 'LEADS_TO',
  BLOCKED_BY: 'BLOCKED_BY'
};

export const IMPACT_RELATION_TYPES = [
  EDGE_TYPES.SOLVES,
  EDGE_TYPES.USES,
  EDGE_TYPES.EVALUATES_ON,
  EDGE_TYPES.BENCHMARKED_ON,
  EDGE_TYPES.REPORTS,
  EDGE_TYPES.REPORTS_FINDING,
  EDGE_TYPES.CLAIMS,
  EDGE_TYPES.HAS_LIMITATION,
  EDGE_TYPES.ASSUMES,
  EDGE_TYPES.SUGGESTS_FUTURE,
  EDGE_TYPES.SUPPORTED_BY,
  EDGE_TYPES.OBSERVED_ON,
  EDGE_TYPES.MEASURED_BY,
  EDGE_TYPES.APPLIES_TO,
  EDGE_TYPES.TRANSFERABLE_TO,
  EDGE_TYPES.REQUIRES,
  EDGE_TYPES.DEPENDS_ON,
  EDGE_TYPES.FAILS_UNDER,
  EDGE_TYPES.HAS_GAP,
  EDGE_TYPES.RELATED_TO,
  EDGE_TYPES.SIMILAR_TO,
  EDGE_TYPES.COMPATIBLE_WITH,
  EDGE_TYPES.COMBINES_WITH,
  EDGE_TYPES.MAY_BE_ADDRESSED_BY,
  EDGE_TYPES.CONTRADICTS,
  EDGE_TYPES.CITES,
  EDGE_TYPES.LEADS_TO,
  EDGE_TYPES.BLOCKED_BY
];

export function getNodeLayer(nodeType) {
  return NODE_TYPE_TO_LAYER[nodeType] || GRAPH_LAYERS.DOCUMENT;
}
